### ISSUE TITLE
Add more workflow examples and consider creating a template repository

### ISSUE THREAD

**Issue by AlexTMjugador** [ComunidadAylas/PackSquash-action#9]
In the original repositories that sparkled development of this action, @sya-ri included a workflow that created a release on each push, which I think is a nice use for the action: https://github.com/sya-ri/action-PackSquash-Example

Some anecdotal evidence also suggests that downloading the artifact this action generates to do something with it, especially deploying it over SSH, is also pretty common.

Thus, the readme can be improved by including example workflows for those two scenarios.

There was also a template repository for the GitHub Action, that might be useful to get started quickly with it: https://github.com/sya-ri/action-PackSquash-Template

**Comment by sya-ri** [comment]
> Some anecdotal evidence also suggests that downloading the artifact this action generates to do something with it, especially deploying it over SSH, is also pretty common.

Minecraft resource pack loading:
1. The server sends you a URL and hash(pack)
2. Hash the URL
3. Download if no pack matches the hash(url)
4. Test if the hash(pack) sent by the server matches the pack hash

You should not use different packs if they have the same URL. Therefore, it is better to deploy in a different workflow.

For example(deploy.yml):
```yml
name: Deploy
on:
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download pack.zip
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: "pack.zip"
          target: "pack.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Rename file
        run: "mv pack.zip pack-${{ github.run_number }}.zip"
      - name: Upload pack.zip
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "pack-${{ github.run_number }}.zip"
          target: ${{ secrets.DEPLOY_DIRECTORY }}
      - name: Output pazk.zip name
        run: echo "::notice::pack-${{ github.run_number }}.zip"
```
